### ISSUE TITLE
Where to find the csv files of miniImagenet?

### ISSUE THREAD

**Issue by Kongsea** [floodsung/LearningToCompare_FSL#1]
Thank you for your awesome code.
Then I cannot find the csv files of miniImagenet dataset. Could you give me the links or the files?
Thanks.

**Comment by Kongsea** [comment]
I downloaded the second one.
Thank you for your kind help.

**Comment by floodsung** [comment]
https://github.com/twitter/meta-learning-lstm/tree/master/data/miniImagenet

**Comment by Kongsea** [comment]
Thank you very much.
