### ISSUE TITLE
Problem about the feature concatenation

### ISSUE THREAD

**Issue by cultivater** [floodsung/LearningToCompare_FSL#11]
Thank you for your code.
I noticed that before feature concatenation, you sum the feature of support image for each class.
Could you please explain why not concatenate every single support image feature to qurey image feature?  
I have tried that but the result are not as good as before. 
You paper didn't refer to that sum operation so I'm puzzled.

**Comment by floodsung** [comment]
It is just a simple operation to obtain all features. Sum can keep the dimension the same. You can try concatenation too.
