### ISSUE TITLE
MiniImageNet

### ISSUE THREAD

**Issue by Duan-JM** [floodsung/LearningToCompare_FSL#20]

**Comment by Duan-JM** [comment]
Hi,

First of all, I am very appreciate your code. But I ran into a trouble. I can't download the miniImagenet.

I have tried:
1. Use Safari & Chrome retry download [failed]
2. clean the browser cache ,then retry step 1 [failed]
3. use google drive app [failed]
4. ask friend try step 1,2,3 [failed]

So I wonder if the source have some problem. It would be great if you can upload the file to an different drive, such like dropbox? 

![](https://ws3.sinaimg.cn/large/006tKfTcly1g110jwh50aj30bs02p74p.jpg)

**Comment by lxq0204** [comment]
I have download the images.zip.  My mailbox is 1604731382@qq.com.
