### ISSUE TITLE
Problem about the normalization part

### ISSUE THREAD

**Issue by MathildaChen** [floodsung/LearningToCompare_FSL#7]
Thank you for your awesome code.
There is a norm part for both miniimagenet and omniglot data,
"normalize = transforms.Normalize(mean=[0.92206, 0.92206, 0.92206], std=[0.08426, 0.08426, 0.08426])"
but why are the the mean and std values always the same?

**Comment by floodsung** [comment]
We just keep image data with 3d have the same mean and std. It is a common process on Imagenet.
